
export default {
  zh: {
    i18nView: {
      information: {
        keyword: '关键字',
        search: '搜索',
        add: '添加',
        export: '导出',
        id: '序号',
        name: '名称',
        company: '公司名称',
        infoType: '信息类型',
        icon: '图标',
        pic: '图片',
        url: '网址',
        price: '价格',
        ValuationMethod: '计价方式',
        telePhone: '联系电话',
        fax: '传真',
        contacts: '联系人',
        city: '城市',
        hotelType: '酒店类别',
        hotelLevel: '酒店级别',
        address: '地址',
        email: '邮箱',
        website: '官网',
        payType: '支付类型',
        creator: '创建人',
        files: '附件',
        remarks: '备注',
        modifier: '修改者',
        actions: '操作',
        edit: '编辑',
        delete: '删除',
        team: '团队/TEAM',
        fit: '自由行/FIT',
        cancel: '取消',
        confirm: '确定',
        introduce: '介绍',
        unitPrice: '单价',
        packagePrice: '套餐价'
      },
      areas: {
        all: '全部',
        bangkok: '曼谷',
        pattaya: '芭提雅',
        samed: '沙美岛',
        rayong: '罗勇',
        ayutthaya: '大城',
        huahin: '华欣',
        kanchanaburi: '北碧',
        samui: '苏梅岛',
        surat: 'SURAT',
        kohchang: '象岛'
      },
      status: {
        publish: '开启',
        draft: '关闭',
        all: '全部'
      },
      payTypeList: {
        pay: '公司支出(VOUCHER)',
        charges: '公司收费',
        revenue: '公司收入',
        tourGuidePays: '导游支出',
        pays: '公司支出',
        tourGuidePay: '导游支出(VOUCHER)'
      }
    }
  },
  en: {
    i18nView: {
      information: {
        keyword: '关键字',
        search: 'search',
        add: 'add',
        export: 'export',
        id: '序号',
        name: 'name',
        company: 'company',
        infoType: '信息类型',
        icon: '图标',
        pic: '图片',
        url: '网址',
        ValuationMethod: '计价方式',
        price: '价格',
        telePhone: '联系电话',
        fax: '传真',
        contacts: '联系人',
        city: '城市',
        hotelType: '酒店类别',
        hotelLevel: '酒店级别',
        address: '地址',
        email: '邮箱',
        website: '官网',
        payType: '支付类型',
        creator: '创建人',
        files: '附件',
        remarks: '备注',
        modifier: '修改者',
        actions: 'actions',
        edit: 'edit',
        delete: 'delete',
        team: '团队/TEAM',
        fit: '自由行/FIT',
        cancel: '取消',
        confirm: '确定'
      },
      areas: {
        all: 'All',
        bangkok: 'bangkok',
        pattaya: 'pattaya',
        samed: 'samed',
        rayong: 'rayong',
        ayutthaya: 'ayutthaya',
        huahin: 'huahin',
        kanchanaburi: 'kanchanaburi',
        samui: 'samui',
        surat: 'surat',
        kohchang: 'kohchang'
      }
    }
  }
}
