
export default {
  zh: {
    i18nView: {
      information: {
        hotel: '酒店',
        keyword: '关键字',
        search: '搜索',
        add: '添加',
        export: '导出',
        id: '序号',
        name: '酒店名称',
        company: '公司名称',
        infoType: '信息类型',
        icon: '图标',
        pic: '图片',
        url: '网址',
        price: '价格',
        valuationMethod: '计价方式',
        telePhone: '联系电话',
        fax: '传真',
        contacts: '联系人',
        city: '城市',
        hotelType: '酒店类别',
        hotelLevel: '酒店级别',
        address: '地址',
        email: '邮箱',
        website: '官网',
        payType: '支付类型',
        creator: '创建人',
        files: '附件',
        remarks: '备注',
        modifier: '修改者',
        actions: '操作',
        edit: '编辑',
        delete: '删除',
        team: '团队/TEAM',
        fit: '自由行/FIT',
        cancel: '取消',
        confirm: '确定',
        introduce: '介绍'
      },
      areas: {
        all: '全部',
        bangkok: '曼谷',
        pattaya: '芭提雅',
        samed: '沙美岛',
        rayong: '罗勇',
        ayutthaya: '大城',
        huahin: '华欣',
        kanchanaburi: '北碧',
        samui: '苏梅岛',
        surat: 'SURAT',
        kohchang: '象岛'
      },
      status: {
        publish: '开启',
        draft: '关闭',
        all: '全部'
      }
    }
  },
  en: {
    i18nView: {
      information: {
        hotel: 'Hotel',
        keyword: 'keyword',
        search: 'search',
        add: 'add',
        export: 'export',
        id: '序号',
        name: 'HotelName',
        company: 'company',
        infoType: '信息类型',
        icon: 'icon',
        pic: 'image',
        url: 'url',
        valuationMethod: 'valuationMethod',
        price: 'price',
        telePhone: 'telePhone',
        fax: 'fax',
        contacts: 'contacts',
        city: 'city',
        hotelType: 'hotelType',
        hotelLevel: 'hotelLevel',
        address: 'address',
        email: 'email',
        website: 'website',
        payType: 'payType',
        creator: 'creator',
        files: 'files',
        remarks: 'remark',
        modifier: '修改者',
        actions: 'actions',
        edit: 'edit',
        delete: 'delete',
        team: 'TEAM',
        fit: 'FIT',
        cancel: 'cancel',
        confirm: 'confirm'
      },
      areas: {
        all: 'All',
        bangkok: 'bangkok',
        pattaya: 'pattaya',
        samed: 'samed',
        rayong: 'rayong',
        ayutthaya: 'ayutthaya',
        huahin: 'huahin',
        kanchanaburi: 'kanchanaburi',
        samui: 'samui',
        surat: 'SURAT',
        kohchang: 'kohchang'
      }
    }
  }
}
